### ISSUE TITLE
Live HTML Doesn't Get Minified

### ISSUE THREAD

**Issue by mattisdada** [GrahamCampbell/Laravel-HTMLMin#31]
The output for "Automatic Live Optimizations" doesn't really seem to minifiy. At the moment it just breaks up the lines awkwardly with no real space saving. 

Source:
```html
<nav class="top_nav">
    <a href="/repairs">Repairs</a>
    <a href="/services">Services</a>
    <a href="/pricing">Pricing</a>
</nav>
```

Output:
```html
<nav
class="top_nav">
<a
href="/repairs">Repairs</a>
<a
href="/services">Services</a>
<a
href="/pricing">Pricing</a>
</nav>
```

Expected:
```html
<nav class="top_nav"><a href="/repairs">Repairs</a><a href="/services">Services</a><a href="/pricing">Pricing</a></nav>
```

**Comment by GrahamCampbell** [comment]
You're mistaken. That output IS minified. The minifier is just using a newline instead of a space.

**Comment by goyney** [comment]
I'm getting the same output now. How do you change it so it uses a space instead of a newline?

**Comment by GrahamCampbell** [comment]
You can't.

**Comment by GrahamCampbell** [comment]
Take it up with https://github.com/mrclay/minify if you don't like it. Nothing I can really do.

**Comment by goyney** [comment]
Then, might I ask, what is the point of using your plugin to "minify" the HTML if it cannot completely minify it down to one line?

**Comment by GrahamCampbell** [comment]
Because it IS minified. Newline characters are 1 byte as are spaces, so the result is the same size.

**Comment by goyney** [comment]
Sorry, I deleted the comment after I saw your comment about there being nothing you could do because I didn't feel my comment was constructive after that point. But, thank you for still responding to it. You're right, a space/newline are both 1 byte, so it does accomplish that same thing. The OCD in me just would rather see things all on one line. Thanks for the good information. Hopefully, this helps ease anyone else's concerns who might stumble upon this.

**Comment by GrahamCampbell** [comment]
Sure. I do prefer it on one line too, but it's the same size either way so I live with it. Better than trying to write my own algorithm. :)
