### ISSUE TITLE
Blade Extends Layouts.app not minify

### ISSUE THREAD

**Issue by ri7nz** [GrahamCampbell/Laravel-HTMLMin#64]
layouts.app not minify but blade extends from layouts.app is minify
im sorry for my bad english 

![image](https://cloud.githubusercontent.com/assets/16365952/21804919/68dfd114-d76c-11e6-8122-a13bfcf86d17.png)

thanks

**Comment by GrahamCampbell** [comment]
Probably clear your compiled view cache. If not, then it's not being minified because it's not safe to do so. You could force it by enabling the force option.

Alternatively, for best results (smallest output, not fastest execution time), use the minification http middleware. TBH, in most applications, minification is not needed, because the amount it time it takes to minify is larger than the time it takes to transfer those extra bytes across the network.
