### ISSUE TITLE
Config File Not Generated

### ISSUE THREAD

**Issue by ryanthehouse** [GrahamCampbell/Laravel-HTMLMin#76]
I have followed your instruction and even noticed the missing "r" in the service provide(r) per your instruction. On running "php artisan vendor:publish" the config file is not added to Laravel's config folder.

**Comment by bars3s** [comment]
@ryanthehouse try `artisan config:cache` and then `artisan vendor:publish` once again

**Comment by GrahamCampbell** [comment]
> I have followed your instruction and even noticed the missing "r" in the service provide(r) per your instruction.

Thank you. This has now been fixed.

> try artisan config:cache

Yes, that will likely be the cause. I am reluctant to document this though, because it is technically unrelated to this package. The documentation goes with the calling of the cache command in the first place, which was done before this package was installed.

---

Thank you everyone.
